version: "3"
services:
  talker:
    image: sadtalker
    container_name: sadTalker
    volumes:
      - ./results:/app/SadTalker/results
    ports:
      - "80:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
